version: '3'

networks:
  alticci-net:
    driver: bridge

services:
  alticci-api-service:
    build:
      context: ./alticci-quarkus-api
      dockerfile: src/main/docker/Dockerfile.native
    image: alticci-api:native
    ports:
      - '8080:8080'
    networks:
      - alticci-net
